language: ruby
rvm:
  - 2.4.1
before_install:
  - gem update
  - gem install bundler
install:
  - bundle install --retry=3
script:
  - gem build autotune.gemspec
  - gem install autotune*.gem
addons:
  apt:
    packages:
    - libtag1-dev
